/**
 * Builds the storefront's product photography from a small lookbook shoot.
 *
 * The shop has ~10 source frames and ~38 products, which is how a real single
 * shoot gets stretched across a catalogue: each product gets a primary crop
 * (with a light grade when a colourway needs one) plus detail crops for its
 * gallery. Everything is normalised to one 4:5 ratio, one size, one quality —
 * so the grid never jitters and pages stay light.
 *
 * Run: node scripts/build-images.mjs [--force]
 * Output: public/images/derived/*.jpg  (gitignored; regenerated by `npm run setup`)
 */
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { products } from "./catalog.data.mjs";

const ROOT = process.cwd();
const PUBLIC = path.join(ROOT, "public");
const OUT_DIR = path.join(PUBLIC, "images", "derived");
const WIDTH = 1120;
const HEIGHT = 1400;

const GRADES = {
  none: (img) => img,
  bright: (img) => img.modulate({ brightness: 1.33, saturation: 0.6, lightness: 9 }),
  dark: (img) => img.modulate({ brightness: 0.58, saturation: 0.86, lightness: -6 }),
  olive: (img) => img.grayscale().tint({ r: 132, g: 146, b: 96 }).modulate({ brightness: 0.94 }),
  maroon: (img) => img.grayscale().tint({ r: 150, g: 62, b: 66 }).modulate({ brightness: 0.88 }),
  navy: (img) => img.grayscale().tint({ r: 58, g: 80, b: 120 }).modulate({ brightness: 0.92 }),
  sand: (img) => img.grayscale().tint({ r: 208, g: 188, b: 156 }).modulate({ brightness: 1.04 }),
};

export function resolveSource(src) {
  if (!src) return null;
  const local = src.replace(/^\//, "");
  const candidates = [path.join(PUBLIC, local), path.join(ROOT, "public", local), path.join(ROOT, local)];
  return candidates.find((candidate) => fs.existsSync(candidate)) ?? null;
}

async function buildOne(source, spec, outPath) {
  const image = sharp(source, { failOn: "none" }).rotate();
  const meta = await image.metadata();
  const W = meta.width;
  const H = meta.height;

  // crop is [x, y, w, h] in fractions of the source frame
  const [fx = 0, fy = 0, fw = 1, fh = 1] = spec.crop ?? [0, 0, 1, 1];
  const left = Math.max(0, Math.round(fx * W));
  const top = Math.max(0, Math.round(fy * H));
  const width = Math.max(32, Math.min(W - left, Math.round(fw * W)));
  const height = Math.max(32, Math.min(H - top, Math.round(fh * H)));

  let pipeline = image.extract({ left, top, width, height }).resize(WIDTH, HEIGHT, {
    fit: "cover",
    position: (spec.gravity ?? "centre").toString(),
    background: "#f2efe9",
  });
  pipeline = (GRADES[spec.fx ?? "none"] ?? GRADES.none)(pipeline);
  await pipeline.flatten({ background: "#f2efe9" }).jpeg({ quality: 84, progressive: true, mozjpeg: true }).toFile(outPath);
  return { width: WIDTH, height: HEIGHT, bytes: fs.statSync(outPath).size };
}

export async function buildImages({ force = false, quiet = false } = {}) {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const report = { written: 0, skipped: 0, missing: [], byProduct: {} };

  for (const [index, product] of products.entries()) {
    const specs = [];
    if (product.artwork?.src) specs.push({ ...product.artwork, key: "primary" });
    (product.gallery ?? []).forEach((entry, i) => specs.push({ ...entry, src: entry.src ?? product.artwork?.src, key: `g${i + 1}` }));

    if (!specs.length) {
      report.byProduct[product.slug] = [];
      continue;
    }

    const written = [];
    for (const spec of specs) {
      const outName = `${product.slug}-${spec.key}.jpg`;
      const outPath = path.join(OUT_DIR, outName);
      const relPath = `/images/derived/${outName}`;
      const source = resolveSource(spec.src);

      if (!source) {
        // Missing photography is not an error: the UI renders a designed
        // illustrated card for products whose shoot has not happened yet.
        report.missing.push(`${product.slug}: ${spec.src ?? "no source"}`);
        written.push({ src: relPath, alt: product.name, missing: true });
        continue;
      }
      if (fs.existsSync(outPath) && !force) {
        report.skipped += 1;
        written.push({ src: relPath, alt: product.name });
        continue;
      }
      try {
        const info = await buildOne(source, spec, outPath);
        report.written += 1;
        written.push({ src: relPath, alt: product.name, bytes: info.bytes });
        if (!quiet) console.log(`  · ${outName}  ${(info.bytes / 1024).toFixed(0)} kB`);
      } catch (error) {
        console.warn(`  ! could not build ${outName}: ${error.message}`);
        report.missing.push(`${product.slug}: build failed`);
      }
    }
    report.byProduct[product.slug] = written;
  }

  if (!quiet) {
    console.log(`\nImages ready: ${report.written} written, ${report.skipped} unchanged.`);
    if (report.missing.length) {
      console.log(`${report.missing.length} frame(s) will use the illustrated placeholder:`);
      for (const line of report.missing.slice(0, 8)) console.log(`  - ${line}`);
      if (report.missing.length > 8) console.log(`  … and ${report.missing.length - 8} more`);
    }
  }
  return report;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  buildImages({ force: process.argv.includes("--force") }).catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
