/**
 * The demo catalogue for Mens Wear.
 *
 * Kept as a plain data module (not inside the app) so the seeder can run
 * standalone, and so the shop's real launch data can replace this file without
 * touching application code.
 *
 * `artwork` describes which region of a source photograph becomes the product's
 * primary image; `gallery` adds crops of the same shoot as gallery frames —
 * exactly how a real single-day lookbook shoot gets reused across a catalogue.
 */

export const storeProfile = {
  shopName: "Mens Wear",
  tagline: "Considered menswear, cut and checked in-house since 2014",
  phone: "+91 98250 41188",
  whatsapp: "9825041188",
  email: "care@menswear.in",
  addressLine1: "12 Station Road, Rajwadi Corner",
  addressLine2: "Ground floor, below Hotel Shreeji",
  city: "Surat",
  state: "Gujarat",
  pin: "395002",
  hours: "Mon – Sat 10:30 am – 9:00 pm · Sun 11:00 am – 2:00 pm",
  instagram: "https://instagram.com/menswear",
  facebook: "https://facebook.com/menswear",
  announcement: "Free delivery across India above ₹1,999 · Cash on delivery available · Exchange within 7 days",
  whatsappGreeting: "Hello! Tell us the size you wear and we will hold it at the counter.",
  logoText: "M",
};

/** Order matters: this is the order the owner sees in the nav and filters. */
export const categories = [
  { name: "T-Shirts", slug: "t-shirts", blurb: "Heavyweight cotton, combed and bio-washed", image: "/images/products/tee-oversized-ecru.jpg", subs: ["Crew Neck", "Polo", "Oversized"] },
  { name: "Shirts", slug: "shirts", blurb: "Oxford, linen and formal two-ply", image: "/images/products/shirt-linen-sand.jpg", subs: ["Formal", "Casual", "Linen"] },
  { name: "Jeans", slug: "jeans", blurb: "Comfort-stretch denim, 12 oz and up", image: "/images/products/jeans-indigo-slim.jpg", subs: ["Slim", "Straight", "Tapered"] },
  { name: "Trousers", slug: "trousers", blurb: "Chinos, wool blends and formal pleats", image: "/images/hero-editorial.jpg", subs: ["Chinos", "Formal", "Cargo"] },
  { name: "Formal Wear", slug: "formal-wear", blurb: "Suits and dress shirts for the occasions that matter", image: "/images/banner-tailoring.jpg", subs: ["Suits", "Dress Shirts", "Waistcoats"] },
  { name: "Casual Wear", slug: "casual-wear", blurb: "Weekend sets, overshirts and everyday layers", image: "/images/banner-sale.jpg", subs: ["Everyday", "Weekend"] },
  { name: "Jackets", slug: "jackets", blurb: "Bombers, denim and utility layers", image: null, subs: ["Bomber", "Denim", "Overshirt"] },
  { name: "Hoodies", slug: "hoodies", blurb: "340 GSM fleece, brushed inside", image: null, subs: ["Pullover", "Zip-through"] },
  { name: "Sweaters", slug: "sweaters", blurb: "Merino and cotton knits for winter evenings", image: null, subs: ["Crew Neck", "Cardigan"] },
  { name: "Blazers", slug: "blazers", blurb: "Unstructured shoulders, half-canvas", image: "/images/hero-editorial.jpg", subs: ["Single-Breasted", "Linen Blend"] },
  { name: "Ethnic Wear", slug: "ethnic-wear", blurb: "Kurta sets, Nehru jackets and festive weaves", image: "/images/hero-ethnic.jpg", subs: ["Kurta Sets", "Nehru Jacket", "Festive"] },
  { name: "Kurta", slug: "kurta", blurb: "Handloom cotton, slub linen, day-to-night cuts", image: "/images/hero-ethnic.jpg", subs: ["Cotton", "Linen", "Festive"] },
  { name: "Shorts", slug: "shorts", blurb: "Above-knee chino and dry-fit shorts", image: null, subs: ["Chino", "Dry-fit"] },
  { name: "Track Pants", slug: "track-pants", blurb: "Tapered joggers with zip pockets", image: null, subs: ["Joggers", "Cotton"] },
];

/** Collections are flags on products, not categories — so a product can be new *and* on sale. */
export const collections = [
  { key: "new", name: "New Arrivals", blurb: "Fresh off the rail this week", slug: "new-arrivals" },
  { key: "bestsellers", name: "Best Sellers", blurb: "What the shop keeps reordering", slug: "best-sellers" },
  { key: "sale", name: "Sale", blurb: "Reduced while the lot lasts", slug: "sale" },
];

export const colorLibrary = [
  { name: "Ecru", hex: "#EDE6D8" },
  { name: "Charcoal", hex: "#3A3C3E" },
  { name: "Midnight", hex: "#1F2937" },
  { name: "Sky", hex: "#A8C3D9" },
  { name: "White", hex: "#F7F7F5" },
  { name: "Sand", hex: "#CBB79A" },
  { name: "Sage", hex: "#8C9B7E" },
  { name: "Indigo", hex: "#2F4266" },
  { name: "Washed Black", hex: "#252527" },
  { name: "Tan", hex: "#B8946A" },
  { name: "Navy", hex: "#22314F" },
  { name: "Olive", hex: "#5F6B45" },
  { name: "Camel", hex: "#C0A080" },
  { name: "Maroon", hex: "#5D2A32" },
  { name: "Grey Melange", hex: "#9A9C9E" },
  { name: "Ivory", hex: "#F1EBDD" },
];

export const alphaSizes = ["XS", "S", "M", "L", "XL", "XXL"];
export const waistSizes = ["28", "30", "32", "34", "36", "38"];
export const shirtSizes = ["38", "40", "42", "44", "46", "48"];
export const blazerSizes = ["38", "40", "42", "44", "46", "48", "50"];
export const kurtaSizes = ["S", "M", "L", "XL", "XXL", "Free"];

const CARE_COTTON =
  "Machine wash cold on gentle, inside out. Do not bleach. Line dry in shade; warm iron reverse side. Dry clean only if the label tag is still attached.";
const CARE_DENIM =
  "First wash separately in cold water to set the indigo. Wash inside out, once every 6–8 wears. Air dry, no tumble — it keeps the stretch honest.";
const CARE_LINEN =
  "Machine wash cold or hand wash. Tumble low and remove while damp, then steam-iron for that crisp summer crease. Dry clean for a sharper finish.";
const CARE_WOOL =
  "Dry clean recommended. Between cleans, spot wipe with a damp cloth and air on a wide hanger for six hours. Store with a cedar block, never in a plastic cover.";
const CARE_KNIT =
  "Hand wash cold with a wool-safe detergent. Do not wring — press water out in a towel and dry flat. Fold for storage; never hang a knit.";
const CARE_ETHNIC =
  "Dry clean the first wash to protect the weave. After that, hand wash cold, line dry in shade and iron on the reverse with a cloth guard.";
const CARE_FLEECE =
  "Machine wash cold inside out with like colours. No fabric softener — it flattens the brushed inside. Tumble dry low.";

/**
 * The catalogue. `artwork.src` + `artwork.crop` are consumed by
 * scripts/build-images.mjs, which writes the actual files into
 * public/images/derived/ before the DB rows are inserted.
 */
export const products = [
  {
    name: "Boxy Oversized Cotton Tee",
    slug: "boxy-oversized-cotton-tee",
    category: "t-shirts",
    sub: "Oversized",
    brand: "Mens Wear Studio",
    price: 995,
    mrp: 1599,
    colors: ["Ecru", "Midnight", "Sage"],
    sizes: alphaSizes,
    featured: true,
    isNew: true,
    bestseller: true,
    fabric: "240 GSM combed cotton, single jersey, pre-shrunk and bio-washed for a dry hand-feel.",
    description:
      "The tee we rebuilt four times before we were happy with it. Drop shoulder, a slightly boxy body that sits off the torso in summer heat, and a ribbed collar taped at the back so it never stretches out after a month. Cut 1.5 inches longer than a regular fit so it stays put when you raise your arms.",
    care: CARE_COTTON,
    artwork: { src: "/images/products/tee-oversized-ecru.jpg", crop: [0, 0, 1, 1] },
    gallery: [
      { crop: [0.18, 0.02, 0.64, 0.46] },
      { crop: [0.05, 0.45, 0.9, 0.55] },
    ],
  },
  {
    name: "Pima Cotton Crew Tee",
    slug: "pima-cotton-crew-tee",
    category: "t-shirts",
    sub: "Crew Neck",
    brand: "Northbound",
    price: 1195,
    mrp: 1799,
    colors: ["Charcoal", "White", "Midnight"],
    sizes: alphaSizes,
    bestseller: true,
    fabric: "190 GSM Peruvian Pima blend cotton with a matte finish and side-locked seams.",
    description:
      "A slimmer, cleaner tee for wearing under a blazer or on its own in AC. Pima's longer staple means the surface stays smooth instead of pilling at the underarm after three washes.",
    care: CARE_COTTON,
    artwork: { src: "/images/products/tee-pima-charcoal.jpg", crop: [0, 0, 1, 1] },
    gallery: [{ crop: [0.2, 0.0, 0.62, 0.44] }, { crop: [0.12, 0.5, 0.78, 0.5] }],
  },
  {
    name: "Heavyweight Cotton Polo",
    slug: "heavyweight-polo-tipped-collar",
    category: "t-shirts",
    sub: "Polo",
    brand: "Monarch & Co",
    price: 1395,
    mrp: 2199,
    colors: ["White", "Navy", "Olive"],
    sizes: alphaSizes,
    fabric: "220 GSM cotton piqué with a fused-free collar and three horn-look buttons.",
    description:
      "Piqué with real depth, so the collar stands after a season of washes. The placket is cut long enough to stay closed when you tuck it in — a small thing that decides whether a polo looks expensive.",
    care: CARE_COTTON,
    artwork: { src: "/images/products/tee-pima-charcoal.jpg", crop: [0.16, 0.0, 0.68, 0.52] },
    gallery: [{ crop: [0.28, 0.06, 0.44, 0.4] }],
  },
  {
    name: "Everyday Tee 3-Pack",
    slug: "everyday-tee-3-pack",
    category: "t-shirts",
    sub: "Crew Neck",
    brand: "Mens Wear Studio",
    price: 2299,
    mrp: 3897,
    colors: ["White", "Charcoal", "Midnight"],
    sizes: alphaSizes,
    isNew: false,
    featured: false,
    fabric: "Three 200 GSM combed cotton crew necks: one white, one charcoal, one navy.",
    description:
      "The pack customers ask us to restock every month. Undershirt-weight cotton, flat-lock seams, no logo on the chest. Buy the pack, keep the drawer sorted.",
    care: CARE_COTTON,
    artwork: { src: "/images/banner-sale.jpg", crop: [0.06, 0.05, 0.5, 0.95] },
    gallery: [{ src: "/images/products/tee-oversized-ecru.jpg", crop: [0.3, 0.1, 0.42, 0.42] }],
  },
  {
    name: "Baby Blue Oxford Button-Down",
    slug: "baby-blue-oxford-button-down",
    category: "shirts",
    sub: "Casual",
    brand: "Karnav",
    price: 1745,
    mrp: 2599,
    colors: ["Sky", "White", "Sage"],
    sizes: shirtSizes,
    featured: true,
    bestseller: true,
    fabric: "130 GSM cotton oxford with a button-down collar and a curved hem.",
    description:
      "The one shirt that works with denim, chinos and a navy suit. Woven oxford gives it texture so it never looks like office laundry, and the collar rolls rather than folds — that roll is the whole point.",
    care: CARE_COTTON,
    artwork: { src: "/images/products/shirt-oxford-sky.jpg", crop: [0, 0, 1, 1] },
    gallery: [{ crop: [0.24, 0.0, 0.56, 0.4] }, { crop: [0.1, 0.42, 0.8, 0.58] }],
  },
  {
    name: "Pure Linen Camp-Collar Shirt",
    slug: "pure-linen-camp-collar-shirt",
    category: "shirts",
    sub: "Linen",
    brand: "Sutra Thread",
    price: 2145,
    mrp: 3199,
    colors: ["Sand", "White", "Sage"],
    sizes: shirtSizes,
    isNew: true,
    featured: true,
    fabric: "100% European flax linen, 180 GSM, garment-washed with a single patch pocket.",
    description:
      "Built for 38°C. Open camp collar, boxy through the chest, sleeves cut to roll once without fighting you. Linen creases — that is the fabric talking, not a fault.",
    care: CARE_LINEN,
    artwork: { src: "/images/products/shirt-linen-sand.jpg", crop: [0, 0, 1, 1] },
    gallery: [{ crop: [0.22, 0.03, 0.6, 0.44] }, { crop: [0.06, 0.46, 0.86, 0.54] }],
  },
  {
    name: "Black Spread-Collar Dress Shirt",
    slug: "black-spread-collar-dress-shirt",
    category: "shirts",
    sub: "Formal",
    brand: "Monarch & Co",
    price: 1895,
    mrp: 2899,
    colors: ["Washed Black", "White", "Midnight"],
    sizes: shirtSizes,
    fabric: "Two-ply 100s Giza cotton, matte resin finish, reinforced placket.",
    description:
      "A black shirt that reads formal, not club-wear: matte two-ply, a spread collar that sits under a lapel, and a rear yoke cut on the bias so it moves when you shake hands.",
    care: CARE_COTTON,
    artwork: { src: "/images/products/shirt-black-spread.jpg", crop: [0, 0, 1, 1] },
    gallery: [{ crop: [0.26, 0.0, 0.5, 0.38] }],
  },
  {
    name: "Two-Ply Formal Shirt — Cutaway Collar",
    slug: "two-ply-formal-shirt-cutaway-collar",
    category: "shirts",
    sub: "Formal",
    brand: "Karnav",
    price: 1645,
    mrp: 2399,
    colors: ["White", "Sky", "Charcoal"],
    sizes: shirtSizes,
    bestseller: true,
    fabric: "Cotton poplin with a wrinkle-resistant finish, cut-away collar and single-button cuff.",
    description:
      "For the eleven-hour days and the wedding you fly to afterwards. Irons in four minutes, survives a full day inside a jacket, and the collar stand is tall enough to hide a tie knot.",
    care: CARE_COTTON,
    artwork: { src: "/images/products/shirt-black-spread.jpg", crop: [0.14, 0.0, 0.72, 0.6] },
    gallery: [{ src: "/images/products/shirt-oxford-sky.jpg", crop: [0.3, 0.05, 0.42, 0.34] }],
  },
  {
    name: "Linen-Cotton Half-Placket Shirt",
    slug: "linen-cotton-half-placket-shirt",
    category: "shirts",
    sub: "Casual",
    brand: "Sutra Thread",
    price: 1995,
    mrp: 2899,
    colors: ["Olive", "Sand", "White"],
    sizes: shirtSizes,
    isNew: true,
    fabric: "Linen-cotton blend (60/40), half placket, coconut-shell buttons.",
    description:
      "Half the fuss of a full button-down. The blend keeps the linen's breath and loses some of its temper, so it survives a monsoon commute.",
    care: CARE_LINEN,
    artwork: { src: "/images/products/shirt-linen-sand.jpg", crop: [0.16, 0.0, 0.68, 0.56] },
    gallery: [{ crop: [0.1, 0.4, 0.8, 0.6] }],
  },
  {
    name: "Raw Indigo Slim Jeans",
    slug: "raw-indigo-slim-jeans",
    category: "jeans",
    sub: "Slim",
    brand: "Roadsmith",
    price: 2595,
    mrp: 3999,
    colors: ["Indigo", "Washed Black"],
    sizes: waistSizes,
    featured: true,
    bestseller: true,
    fabric: "13.5 oz selvedge-look denim, 2% elastane, chain-stitched hem, brown leather patch.",
    description:
      "Sanforised so it will not shrink on you, with just enough stretch to sit down in. Fades at the knee and wallet in nine weeks — that is the plan.",
    care: CARE_DENIM,
    artwork: { src: "/images/products/jeans-indigo-slim.jpg", crop: [0, 0, 1, 1] },
    gallery: [{ crop: [0.16, 0.0, 0.7, 0.4] }, { crop: [0.2, 0.52, 0.6, 0.48] }],
  },
  {
    name: "Comfort-Stretch Tapered Jeans",
    slug: "comfort-stretch-tapered-jeans",
    category: "jeans",
    sub: "Tapered",
    brand: "Roadsmith",
    price: 2295,
    mrp: 3599,
    colors: ["Washed Black", "Indigo"],
    sizes: waistSizes,
    isNew: true,
    fabric: "11 oz comfort-stretch denim with a pigment wash and antique hardware.",
    description:
      "A taper that is honest about the thigh and narrow from the knee down. The black is garment-dyed twice, so it fades to charcoal rather than grey.",
    care: CARE_DENIM,
    artwork: { src: "/images/products/jeans-indigo-slim.jpg", crop: [0.06, 0.08, 0.86, 0.92] },
    gallery: [{ crop: [0.22, 0.55, 0.56, 0.45] }],
  },
  {
    name: "Straight-Leg Clean Denim",
    slug: "straight-leg-clean-denim",
    category: "jeans",
    sub: "Straight",
    brand: "Northbound",
    price: 2095,
    mrp: 3299,
    colors: ["Indigo", "Midnight"],
    sizes: waistSizes,
    fabric: "12.5 oz non-stretch rigid denim, one-wash, reinforced back pockets.",
    description:
      "No stretch, no taper, no logos. For the man who wants his jeans to last a decade and look better each year.",
    care: CARE_DENIM,
    artwork: { src: "/images/products/jeans-indigo-slim.jpg", crop: [0.02, 0.0, 0.96, 0.72] },
    gallery: [{ src: "/images/banner-tailoring.jpg", crop: [0.3, 0.2, 0.44, 0.6] }],
  },
  {
    name: "Tan Cotton Twill Chinos",
    slug: "tan-cotton-twill-chinos",
    category: "trousers",
    sub: "Chinos",
    brand: "Karnav",
    price: 1795,
    mrp: 2699,
    colors: ["Tan", "Navy", "Olive", "Sand"],
    sizes: waistSizes,
    bestseller: true,
    fabric: "98% cotton / 2% elastane 3/2 twill, 280 GSM, bar-tacked pockets.",
    description:
      "Flat front, a hook-and-bar closure instead of a cheap button, and a hem cut for a 1.5-inch break. The trouser that carries a whole trip: office Monday, dinner Friday.",
    care: CARE_COTTON,
    artwork: { src: "/images/hero-editorial.jpg", crop: [0.16, 0.46, 0.44, 0.54] },
    gallery: [{ crop: [0.24, 0.5, 0.3, 0.5] }],
  },
  {
    name: "Grey Wool-Blend Formal Trousers",
    slug: "grey-wool-blend-formal-trousers",
    category: "trousers",
    sub: "Formal",
    brand: "Monarch & Co",
    price: 2495,
    mrp: 3799,
    colors: ["Charcoal", "Midnight", "Sand"],
    sizes: waistSizes,
    fabric: "70% wool / 30% viscous tropical wool with side adjusters and a clean 32-inch inseam.",
    description:
      "Cut to be worn without a belt — the side adjusters do the work. Holds a crease through a full day of meetings and gives back when you sit.",
    care: CARE_WOOL,
    artwork: { src: "/images/hero-editorial.jpg", crop: [0.13, 0.42, 0.5, 0.58] },
    gallery: [{ crop: [0.2, 0.55, 0.36, 0.45] }],
  },
  {
    name: "Ripstop Utility Trouser",
    slug: "utility-cargo-trouser",
    category: "trousers",
    sub: "Cargo",
    brand: "Roadsmith",
    price: 1895,
    mrp: 2899,
    colors: ["Olive", "Washed Black", "Tan"],
    sizes: waistSizes,
    isNew: true,
    fabric: "Ripstop cotton canvas with bartacked cargo pockets and an adjustable hem drawcord.",
    description:
      "Tapered so it reads intentional, not military surplus. The pockets take a phone and a wallet without sagging.",
    care: CARE_COTTON,
    artwork: { src: "/images/products/jeans-indigo-slim.jpg", crop: [0.0, 0.16, 1.0, 0.84] },
    gallery: [],
  },
  {
    name: "Charcoal Wool Two-Piece Suit",
    slug: "charcoal-wool-two-piece-suit",
    pay: "online",
    days: 9,
    category: "formal-wear",
    sub: "Suits",
    brand: "Monarch & Co",
    price: 12995,
    mrp: 19999,
    colors: ["Charcoal", "Midnight", "Washed Black"],
    sizes: blazerSizes,
    featured: true,
    bestseller: true,
    lowStock: 4,
    fabric: "Half-canvas construction, 110s VBC superfine wool, Bemberg lining, working cuffs.",
    description:
      "Our house fit: a soft shoulder, a gentle waist suppression and a lapel that stops at 3.4 inches so it still looks right in five years. Trousers finished at 32 inches — we hem to your length free of charge in store.",
    care: CARE_WOOL,
    artwork: { src: "/images/hero-editorial.jpg", crop: [0.14, 0.0, 0.46, 0.98] },
    gallery: [
      { src: "/images/banner-tailoring.jpg", crop: [0.1, 0.1, 0.6, 0.85] },
      { crop: [0.22, 0.02, 0.32, 0.42] },
      { crop: [0.18, 0.44, 0.42, 0.5] },
    ],
  },
  {
    name: "Navy Wedding-Season Suit",
    slug: "navy-wedding-season-suit",
    pay: "online",
    days: 10,          // cut and stitched after the order, so it is prepaid
    category: "formal-wear",
    sub: "Suits",
    brand: "Virendra & Co",
    price: 14495,
    mrp: 21999,
    colors: ["Navy", "Midnight"],
    sizes: blazerSizes,
    featured: true,
    fabric: "Deep navy tropical wool with a subtle bird's-eye weave, peak lapel, two-button front.",
    description:
      "For the season of sangeet and reception lunches. The peak lapel and a slightly higher button stance photograph well under warm light — which is exactly what a wedding marquee is.",
    care: CARE_WOOL,
    artwork: { src: "/images/banner-tailoring.jpg", crop: [0.14, 0.06, 0.58, 0.88] },
    gallery: [{ src: "/images/hero-editorial.jpg", crop: [0.2, 0.02, 0.34, 0.6] }],
  },
  {
    name: "Silk-Blend Wedding Waistcoat",
    slug: "ivory-formal-waistcoat",
    category: "formal-wear",
    sub: "Waistcoats",
    brand: "Virendra & Co",
    price: 3995,
    mrp: 5999,
    colors: ["Ivory", "Sand", "Maroon"],
    sizes: blazerSizes,
    isNew: true,
    fabric: "Raw silk-cotton with a self-fabric back and five adjustable brass hooks.",
    description:
      "Wear it over a kurta or under a bandhgala. Cut short at the waist so the kurta below it can breathe.",
    care: CARE_ETHNIC,
    artwork: { src: "/images/products/shirt-black-spread.jpg", crop: [0.2, 0.1, 0.6, 0.5] },
    gallery: [],
  },
  {
    name: "Unstructured Charcoal Linen Blazer",
    slug: "unstructured-charcoal-linen-blazer",
    category: "blazers",
    sub: "Linen Blend",
    brand: "Mens Wear Studio",
    price: 6495,
    mrp: 9999,
    colors: ["Charcoal", "Sand", "Navy"],
    sizes: blazerSizes,
    featured: true,
    isNew: true,
    lowStock: 3,
    fabric: "Linen-wool-silk blend, unlined body, patch pockets, hand-padded lapel roll.",
    description:
      "A jacket for a warm city: no canvas, no lining, folded into a bag without a complaint. The hand-padded lapel is the only place we spent money — it is the only place anyone looks.",
    care: CARE_WOOL,
    artwork: { src: "/images/hero-editorial.jpg", crop: [0.2, 0.0, 0.36, 0.56] },
    gallery: [{ src: "/images/banner-tailoring.jpg", crop: [0.2, 0.14, 0.5, 0.7] }, { crop: [0.14, 0.02, 0.46, 0.6] }],
  },
  {
    name: "Single-Breasted Office Blazer",
    slug: "single-breasted-office-blazer",
    category: "blazers",
    sub: "Single-Breasted",
    brand: "Monarch & Co",
    price: 7495,
    mrp: 11999,
    colors: ["Midnight", "Charcoal", "Washed Black"],
    sizes: blazerSizes,
    fabric: "Four-season wool-blend suiting, half-canvas front, four-button cuff, center vent.",
    description:
      "The safe choice that still looks sharp: two buttons, notch lapel, a chest line long enough to cover a shirt tucked for ten hours.",
    care: CARE_WOOL,
    artwork: { src: "/images/hero-editorial.jpg", crop: [0.16, 0.02, 0.44, 0.72] },
    gallery: [{ crop: [0.26, 0.04, 0.26, 0.4] }],
  },
  {
    name: "Matte Nylon Bomber Jacket",
    slug: "matte-nylon-bomber-jacket",
    category: "jackets",
    sub: "Bomber",
    brand: "Northbound",
    price: 3795,
    mrp: 5999,
    colors: ["Washed Black", "Olive", "Midnight"],
    sizes: alphaSizes,
    featured: true,
    fabric: "Water-repellent matte nylon shell, quilted polyfill, ribbed storm cuffs and hem.",
    description:
      "December in the city is 12°C and windy, not snowy. This is the layer for that — a shell that blocks the wind, a lining that holds warmth, and enough room for a hoodie underneath.",
    care: CARE_FLEECE,
    artwork: null,
    gallery: [],
  },
  {
    name: "Rigid Denim Trucker Jacket",
    slug: "rigid-denim-trucker-jacket",
    pay: "cod",           // ships heavy; the shop prefers cash at the door
    category: "jackets",
    sub: "Denim",
    brand: "Roadsmith",
    price: 3295,
    mrp: 4999,
    colors: ["Indigo", "Washed Black"],
    sizes: alphaSizes,
    isNew: true,
    fabric: "12 oz rigid denim, copper rivets, adjustable tab at the hem.",
    description:
      "Cut short in the body so it sits at the belt over a tee. Wear it for two years and the elbows will tell you what you have been doing.",
    care: CARE_DENIM,
    artwork: null,
    gallery: [],
  },
  {
    name: "Cotton Overshirt Jacket",
    slug: "cotton-overshirt-jacket",
    category: "jackets",
    sub: "Overshirt",
    brand: "Sutra Thread",
    price: 2695,
    mrp: 3999,
    colors: ["Olive", "Sand", "Charcoal"],
    sizes: alphaSizes,
    fabric: "Heavy 10 oz cotton twill, four front pockets, corozo buttons.",
    description:
      "Thin enough to wear as a shirt, warm enough to replace a light jacket. Our most-recommended layer for October and March.",
    care: CARE_COTTON,
    artwork: { src: "/images/banner-sale.jpg", crop: [0.44, 0.06, 0.34, 0.8] },
    gallery: [],
  },
  {
    name: "Brushed Fleece Pullover Hoodie",
    slug: "brushed-fleece-pullover-hoodie",
    category: "hoodies",
    sub: "Pullover",
    brand: "Northbound",
    price: 2295,
    mrp: 3499,
    colors: ["Grey Melange", "Washed Black", "Navy"],
    sizes: alphaSizes,
    bestseller: true,
    fabric: "340 GSM cotton-poly fleece, brushed inside, double-layer hood, metal-tipped drawcords.",
    description:
      "A hoodie that keeps its shape: the hood is lined with a second layer so it stands, and the kangaroo pocket is bartacked at all four corners.",
    care: CARE_FLEECE,
    artwork: null,
    gallery: [],
  },
  {
    name: "Full-Zip Tech Hoodie",
    slug: "full-zip-tech-hoodie",
    category: "hoodies",
    sub: "Zip-through",
    brand: "Roadsmith",
    price: 2695,
    mrp: 3999,
    colors: ["Midnight", "Olive"],
    sizes: alphaSizes,
    isNew: true,
    fabric: "Double-knit polyester-cotton with a YKK zip and hidden thumbhole cuffs.",
    description:
      "For morning walks and the drive to the office. Wicks rather than soaks, and the zip garage stops the collar chafing your chin.",
    care: CARE_FLEECE,
    artwork: null,
    gallery: [],
  },
  {
    name: "Fine Merino Crew-Neck Knit",
    slug: "merino-crew-neck-sweater",
    category: "sweaters",
    sub: "Crew Neck",
    brand: "Virendra & Co",
    price: 3295,
    mrp: 4999,
    colors: ["Camel", "Charcoal", "Navy", "Maroon"],
    sizes: alphaSizes,
    featured: true,
    lowStock: 4,
    fabric: "100% extra-fine merino, 12-gauge, fully fashioned shoulders, ribbed neck.",
    description:
      "Thin enough for a shirt and tie, warm enough to skip the jacket on a 10°C morning. Fully fashioned means the sleeve is knitted to shape rather than cut from a panel — it will not bag out at the elbow.",
    care: CARE_KNIT,
    artwork: null,
    gallery: [],
  },
  {
    name: "Fisherman Cable Knit Sweater",
    slug: "fisherman-cable-knit-sweater",
    category: "sweaters",
    sub: "Crew Neck",
    brand: "Northbound",
    price: 2895,
    mrp: 4299,
    colors: ["Ivory", "Grey Melange"],
    sizes: alphaSizes,
    isNew: true,
    fabric: "Chunky 7-gauge cotton-acrylic cable knit with saddle shoulders.",
    description:
      "The heavy cable our regulars buy as a gift. Saddle shoulders mean it fits across the back even over a shirt.",
    care: CARE_KNIT,
    artwork: null,
    gallery: [],
  },
  {
    name: "Merino Wool Cardigan",
    slug: "merino-wool-cardigan",
    category: "sweaters",
    sub: "Cardigan",
    brand: "Monarch & Co",
    price: 3495,
    mrp: 5299,
    colors: ["Charcoal", "Camel"],
    sizes: alphaSizes,
    fabric: "Merino-blend 14-gauge knit, horn buttons, two patch pockets.",
    description:
      "For the office where the AC is set to arctic. Layer it over a shirt and it reads considered rather than sleepy.",
    care: CARE_KNIT,
    artwork: null,
    gallery: [],
  },
  {
    name: "Handloom Cotton Kurta",
    slug: "handloom-cotton-kurta",
    category: "kurta",
    sub: "Cotton",
    brand: "Sutra Thread",
    price: 1895,
    mrp: 2899,
    colors: ["Ivory", "Sand", "Sage"],
    sizes: kurtaSizes,
    featured: true,
    bestseller: true,
    fabric: "Handloom 80-count cotton with a natural slub, side slits and a mandarin collar.",
    description:
      "Woven on a pit loom in Gujarat, so the width has small irregularities — that is the signature, not a defect. Cut long at 44 inches to fall just below the knee.",
    care: CARE_ETHNIC,
    artwork: { src: "/images/hero-ethnic.jpg", crop: [0.16, 0.0, 0.52, 0.98] },
    gallery: [{ crop: [0.3, 0.04, 0.34, 0.5] }, { crop: [0.1, 0.44, 0.62, 0.56] }],
  },
  {
    name: "Slub Linen Kurta — Half Sleeve",
    slug: "slub-linen-kurta-half-sleeve",
    category: "kurta",
    sub: "Linen",
    brand: "Sutra Thread",
    price: 2295,
    mrp: 3499,
    colors: ["Sand", "White", "Olive"],
    sizes: kurtaSizes,
    isNew: true,
    fabric: "120 GSM slub linen, half placket with a drawstring, curved hem.",
    description:
      "For a Sunday lunch in June. Breathes like nothing else in the shop and looks better the more it is washed.",
    care: CARE_LINEN,
    artwork: { src: "/images/hero-ethnic.jpg", crop: [0.26, 0.02, 0.42, 0.7] },
    gallery: [{ crop: [0.34, 0.3, 0.3, 0.5] }],
  },
  {
    name: "Jacquard Silk-Blend Festive Kurta",
    slug: "jacquard-silk-blend-festive-kurta",
    pay: "online",
    category: "kurta",
    sub: "Festive",
    brand: "Virendra & Co",
    price: 4495,
    mrp: 6999,
    colors: ["Maroon", "Midnight", "Ivory"],
    sizes: kurtaSizes,
    lowStock: 4,
    fabric: "Art-silk blend with tone-on-tone jacquard and hand-finished chikan detail at the placket.",
    description:
      "Diwali, a nikah, an anniversary dinner. It has just enough sheen to catch a bulb without turning into a costume.",
    care: CARE_ETHNIC,
    artwork: { src: "/images/hero-ethnic.jpg", crop: [0.06, 0.14, 0.62, 0.86] },
    gallery: [{ src: "/images/banner-tailoring.jpg", crop: [0.28, 0.1, 0.5, 0.8] }],
  },
  {
    name: "Cotton Kurta Pyjama Set",
    slug: "cotton-kurta-pyjama-set",
    category: "ethnic-wear",
    sub: "Kurta Sets",
    brand: "Sutra Thread",
    price: 2795,
    mrp: 4299,
    colors: ["Ivory", "Sand", "Sage"],
    sizes: kurtaSizes,
    bestseller: true,
    fabric: "Kurta and matching cotton pyjama with an elasticated drawstring waist.",
    description:
      "One purchase, whole evening sorted. The pyjama is cut with a proper taper so it works with a jacket if the function runs late.",
    care: CARE_ETHNIC,
    artwork: { src: "/images/hero-ethnic.jpg", crop: [0.1, 0.2, 0.56, 0.8] },
    gallery: [{ crop: [0.16, 0.04, 0.44, 0.5] }],
  },
  {
    name: "Nehru Jacket — Bandhgala",
    slug: "nehru-jacket-bandhgala",
    days: 7,
    category: "ethnic-wear",
    sub: "Nehru Jacket",
    brand: "Virendra & Co",
    price: 4995,
    mrp: 7999,
    colors: ["Maroon", "Midnight", "Sand"],
    sizes: blazerSizes,
    featured: true,
    isNew: true,
    lowStock: 3,
    fabric: "Raw silk with a mandarin collar, six brass-look buttons and a tonal brocade back.",
    description:
      "The layer that makes a plain kurta look like an occasion. Structure through the chest, no padding at the shoulder.",
    care: CARE_ETHNIC,
    artwork: { src: "/images/hero-ethnic.jpg", crop: [0.28, 0.0, 0.44, 0.62] },
    gallery: [
      { src: "/images/banner-tailoring.jpg", crop: [0.12, 0.1, 0.5, 0.8] },
      { src: "/images/hero-ethnic.jpg", crop: [0.1, 0.2, 0.6, 0.78] },
    ],
  },
  {
    name: "Chino Shorts — 6 Inch Inseam",
    slug: "chino-shorts-6-inch-inseam",
    category: "shorts",
    sub: "Chino",
    brand: "Karnav",
    price: 1295,
    mrp: 1999,
    colors: ["Sand", "Olive", "Navy", "Washed Black"],
    sizes: waistSizes,
    isNew: true,
    fabric: "Cotton twill with 2% stretch, 6-inch inseam, triple-stitched hem.",
    description:
      "Short enough for a beach walk, tailored enough for a café. Above the knee always looks more intentional than below.",
    care: CARE_COTTON,
    artwork: null,
    gallery: [],
  },
  {
    name: "Dry-Fit Performance Shorts",
    slug: "dry-fit-performance-shorts",
    category: "shorts",
    sub: "Dry-fit",
    brand: "Roadsmith",
    price: 1095,
    mrp: 1699,
    colors: ["Washed Black", "Midnight"],
    sizes: waistSizes,
    fabric: "Recycled polyester micro-twill with laser-perforated side panels and a zip pocket.",
    description:
      "Gym to terrace in one garment. The liner is mesh, not cotton, so it dries while you walk.",
    care: CARE_FLEECE,
    artwork: null,
    gallery: [],
  },
  {
    name: "Tapered Cotton Joggers",
    slug: "tapered-cotton-joggers",
    category: "track-pants",
    sub: "Joggers",
    brand: "Northbound",
    price: 1595,
    mrp: 2499,
    colors: ["Charcoal", "Navy", "Washed Black"],
    sizes: alphaSizes,
    bestseller: true,
    fabric: "320 GSM cotton fleece with a ribbed cuff, zip pockets and a drawcord waist.",
    description:
      "A jogger that does not look like sleepwear: a slimmer leg, a flat cuff, and pockets deep enough for a phone that stay put when you run for a bus.",
    care: CARE_FLEECE,
    artwork: null,
    gallery: [],
  },
  {
    name: "Track Pants — Side Stripe",
    slug: "track-pants-side-stripe",
    category: "track-pants",
    sub: "Cotton",
    brand: "Roadsmith",
    price: 1395,
    mrp: 2199,
    colors: ["Midnight", "Washed Black"],
    sizes: alphaSizes,
    isNew: true,
    fabric: "Poly-cotton woven shell with a woven tonal stripe and half-elastic waist.",
    description:
      "The retro stripe, cut narrow. Wear it with a white tee and clean sneakers and it stops being gym-wear.",
    care: CARE_FLEECE,
    artwork: null,
    gallery: [],
  },
  {
    name: "Weekend Cotton Set — Tee & Shorts",
    slug: "weekend-cotton-set",
    category: "casual-wear",
    sub: "Weekend",
    brand: "Mens Wear Studio",
    price: 2495,
    mrp: 3894,
    colors: ["Ecru", "Sage", "Midnight"],
    sizes: alphaSizes,
    featured: true,
    fabric: "240 GSM tee and matching 7 oz twill shorts, dyed in the same bath.",
    description:
      "Two pieces, one colour story. Bought mostly for travel, holidays and the eleven days a year nobody wants to think about dressing.",
    care: CARE_COTTON,
    artwork: { src: "/images/products/tee-oversized-ecru.jpg", crop: [0.06, 0.02, 0.88, 0.98] },
    gallery: [{ src: "/images/products/tee-oversized-ecru.jpg", crop: [0.24, 0.44, 0.52, 0.56] }],
  },
  {
    name: "Everyday Layer Bundle",
    slug: "everyday-layer-bundle",
    category: "casual-wear",
    sub: "Everyday",
    brand: "Mens Wear Studio",
    price: 4495,
    mrp: 7497,
    colors: ["Charcoal", "Midnight", "Olive"],
    sizes: alphaSizes,
    fabric: "Any two tees, one overshirt and one pair of joggers, in your sizes.",
    description:
      "Tell us your sizes on WhatsApp and we will assemble this in store: two pima tees, the cotton overshirt, and the fleece joggers. Saves about ₹3,000 against buying separately.",
    care: CARE_COTTON,
    artwork: { src: "/images/banner-sale.jpg", crop: [0.3, 0.02, 0.46, 0.96] },
    gallery: [],
  },
];

/**
 * Stock is written so the demo shows every state a shop actually has:
 * a few sold-out sizes, three low-stock products and one fully out-of-stock item.
 */
export function stockFor(index, sizeIndex, colorIndex, sizeCount) {
  const seed = (index * 977 + sizeIndex * 131 + colorIndex * 37) % 100;
  if (sizeIndex === sizeCount - 1 && colorIndex === 0 && seed % 3 === 0) return 0;
  if (seed < 9) return 1 + (seed % 3);
  return 4 + (seed % 17);
}

export const demoCustomers = [
  { name: "Rohit Menon", mobile: "9825011223", email: "rohit.menon@example.com" },
  { name: "Siddharth Raval", mobile: "9898045521", email: "sid.raval@example.com" },
  { name: "Aditya Kulkarni", mobile: "9769012345", email: "" },
  { name: "Faisal Shaikh", mobile: "9004556677", email: "faisal.s@example.com" },
  { name: "Nikhil Vora", mobile: "9123456789", email: "" },
  { name: "Karan Bhatia", mobile: "9811122233", email: "karan.bhatia@example.com" },
  { name: "Vikram Shetty", mobile: "9988776655", email: "" },
  { name: "Anand Iyer", mobile: "9797989898", email: "anand.iyer@example.com" },
  { name: "Devang Shah", mobile: "9876500123", email: "" },
  { name: "Imran Qureshi", mobile: "9833312345", email: "imran.q@example.com" },
];

export const demoAddresses = [
  { line1: "B-1404, Shreeji Residency, Vesu", line2: "Near Zoom Art Gallery", city: "Surat", state: "Gujarat", pin: "395007" },
  { line1: "12 Rose Villa, SG Highway", line2: "Opp. Iscon", city: "Ahmedabad", state: "Gujarat", pin: "380015" },
  { line1: "Flat 702, Sai Krupa, Chembur East", line2: "", city: "Mumbai", state: "Maharashtra", pin: "400071" },
  { line1: "44 IIInd Cross, Jayanagar 4th Block", line2: "", city: "Bengaluru", state: "Karnataka", pin: "560011" },
  { line1: "Plot 9, Jubilee Hills, Road No. 36", line2: "Above Tanishq", city: "Hyderabad", state: "Telangana", pin: "500033" },
  { line1: "23 Sector 17, Faridabad", line2: "", city: "Delhi NCR", state: "Haryana", pin: "121002" },
];

/** Orders the dashboard needs to look like a shop that has been trading. */
export const demoOrderPlans = [
  { dayOffset: 0, hours: 2, status: "placed", payment: "cod", customer: 0, lines: [[0, "M", "Ecru", 1]] },
  { dayOffset: 0, hours: 5, status: "confirmed", payment: "cod", customer: 3, lines: [[9, "32", "Indigo", 1], [1, "L", "Charcoal", 2]] },
  { dayOffset: 1, hours: 11, status: "processing", payment: "online", customer: 1, lines: [[15, "42", "Charcoal", 1]] },
  { dayOffset: 1, hours: 13, status: "packed", payment: "cod", customer: 5, lines: [[4, "42", "Sky", 1], [12, "32", "Tan", 1]] },
  { dayOffset: 2, hours: 9, status: "shipped", payment: "cod", customer: 2, lines: [[29, "L", "Ivory", 1], [33, "M", "Ivory", 1]] },
  { dayOffset: 2, hours: 16, status: "out_for_delivery", payment: "online", customer: 4, lines: [[23, "XL", "Grey Melange", 1]] },
  { dayOffset: 3, hours: 10, status: "delivered", payment: "cod", customer: 6, lines: [[9, "34", "Indigo", 1], [0, "L", "Ecru", 1]] },
  { dayOffset: 4, hours: 12, status: "delivered", payment: "online", customer: 7, lines: [[15, "40", "Charcoal", 1]] },
  { dayOffset: 5, hours: 15, status: "delivered", payment: "cod", customer: 8, lines: [[25, "L", "Camel", 1], [1, "M", "White", 1]] },
  { dayOffset: 6, hours: 11, status: "cancelled", payment: "cod", customer: 9, lines: [[19, "44", "Midnight", 1]] },
  { dayOffset: 7, hours: 13, status: "delivered", payment: "cod", customer: 0, lines: [[4, "40", "White", 1]] },
  { dayOffset: 9, hours: 10, status: "delivered", payment: "online", customer: 1, lines: [[30, "L", "Sand", 1], [31, "M", "Maroon", 1]] },
  { dayOffset: 11, hours: 14, status: "delivered", payment: "cod", customer: 3, lines: [[12, "30", "Navy", 2]] },
  { dayOffset: 13, hours: 12, status: "delivered", payment: "cod", customer: 5, lines: [[0, "S", "Sage", 1], [0, "M", "Ecru", 1]] },
  { dayOffset: 15, hours: 9, status: "delivered", payment: "online", customer: 2, lines: [[20, "L", "Washed Black", 1]] },
  { dayOffset: 18, hours: 17, status: "delivered", payment: "cod", customer: 4, lines: [[10, "32", "Washed Black", 1]] },
  { dayOffset: 21, hours: 12, status: "delivered", payment: "cod", customer: 6, lines: [[16, "42", "Navy", 1]] },
  { dayOffset: 24, hours: 11, status: "delivered", payment: "online", customer: 8, lines: [[34, "M", "Navy", 1], [35, "L", "Washed Black", 1]] },
  { dayOffset: 27, hours: 10, status: "delivered", payment: "cod", customer: 7, lines: [[27, "M", "Ivory", 1]] },
  { dayOffset: 29, hours: 15, status: "delivered", payment: "cod", customer: 9, lines: [[9, "30", "Indigo", 1]] },
];
